<a href="https://colab.research.google.com/github/akshnataraj/PyTorch-for-DL/blob/master/Tensor_Crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install torch

In [2]:
import torch
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
print(a.dtype)

torch.int64


In [ ]:
print(type(a))

<class 'torch.Tensor'>


In [ ]:
p = np.array([1,2,3,4,5])
tensor_cnv = torch.from_numpy(p)
print(tensor_cnv)
tensor_cnv.type()

#converting back to numpy
print(tensor_cnv.numpy())

tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]


In [ ]:
torch.cuda.is_available()

False

In [ ]:
#Slicing 3D Tensors
x = torch.arange(27).view(3,3,3)
print(x)
print(x[1][1][1]) # 1st element, 1st row, 1st column

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])
tensor(13)


In [ ]:
#slice elements 15 to 17
print(x[1][2])

tensor([15, 16, 17])


In [10]:
#Matrix Multiplication
mat_a = torch.arange(1,7,1).view(2,3)
mat_b = torch.arange(6,12,1).view(3,2)
print(mat_a,mat_b)
print(torch.matmul(mat_a,mat_b))

#or###

mat_a @ mat_b

tensor([[1, 2, 3],
        [4, 5, 6]]) tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])
tensor([[ 52,  58],
        [124, 139]])


tensor([[ 52,  58],
        [124, 139]])

In [13]:
 #Derivatives 
 x = torch.tensor(2.0,requires_grad=True)
 y = 9*x**4 + 2*x**3 + 3*x**2 + 6*x + 1 #some arbitrary function

 y.backward()
 print(x.grad)

 #Partial Derivates
 x = torch.tensor(1.0,requires_grad=True)
 z = torch.tensor(2.0,requires_grad=True)
 y = x**2 + z**3
 y.backward()
 print(x.grad)


tensor(330.)
tensor(2.)


In [ ]:
#Linear Regression
